### ISSUE TITLE
What's "easy"?

### ISSUE THREAD

**Issue by friday** [kiliwalk/eslint-config-easy#1]
Generally "easy" is something intuitive or familiar.

Strict code standards make it easier to develop for some people (I prefer them), but is hard to switch _to_ in an old project.

In which way is this easy?

**Comment by kiliwalk** [comment]
Nothing special about the "easy". 
As you said, it's hard to transform old projects to use the strict code standards such as `javascript standard` or `airbnb` styles. 
So I made a more loose one, so that my old projects can migrate easily.
Mostly, it's just my own coding style. 
Thanks

**Comment by friday** [comment]
Alright 👍
